name: Build

on: [push, pull_request]

jobs:
  cloverExtension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Install global dependencies
        run: |
          sudo yarn global add vsce

      - name: Install dependencies
        working-directory: cloverExtension
        run: yarn

      - name: Build and package
        working-directory: cloverExtension
        run: vsce package --yarn

      - name: Upload extension
        uses: actions/upload-artifact@v2.2.0
        with:
          name: cloverExtension.vsix
          path: cloverExtension.vsix
