name: Build

on: 
  push:
  pull_request:
  release:
    types: [created, edited, released]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 18
        
      - name: Install Yarn
        run: npm install -g yarn vsce

      - name: Install global dependencies
        run: |
          sudo apt update
          sudo apt install -y librsvg2-bin libsecret-1-dev

      - name: Install extension dependencies
        working-directory: cloverExtension
        run: yarn

      - name: Build and package extension
        working-directory: cloverExtension
        run: yarn package

      - name: Upload extension
        uses: actions/upload-artifact@v2.2.0
        with:
          name: cloverExtension.vsix
          path: cloverExtension.vsix

      - name: Install dependencies and build theia
        working-directory: ide
        run: yarn || yarn || yarn

      - name: Download ide plugins
        working-directory: ide
        run: yarn plugins

      - name: Package ide
        working-directory: ide
        run: |
          yarn getnode 
          yarn install --production

      - name: Create deb
        working-directory: package
        run: make package

      - name: Upload deb
        uses: actions/upload-artifact@v2.2.0
        with:
          name: advancedClover.deb
          path: advancedClover.deb
  
  releaseAssets:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs: build
    steps: 
      - name: Download extension artifact 
        uses: actions/download-artifact@v2
        with:
          name: cloverExtension.vsix
        
      - name: Download deb artifact
        uses: actions/download-artifact@v2
        with:
          name: advancedClover.deb
      
      - name: Upload extension release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cloverExtension.vsix
          asset_name: cloverExtension.vsix
          asset_content_type: application/zip

      - name: Upload deb release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./advancedClover.deb
          asset_name: advancedClover.deb
          asset_content_type: application/x-debian-package
      
