name: Build

on: [push, pull_request]

jobs:
  cloverExtension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Install global dependencies
        run: |
          sudo yarn global add vsce

      - name: Install dependencies
        working-directory: cloverExtension
        run: yarn

      - name: Build and package
        working-directory: cloverExtension
        run: yarn package

      - name: Upload extension
        uses: actions/upload-artifact@v2.2.0
        with:
          name: cloverExtension.vsix
          path: cloverExtension.vsix
  
  plugins:
    runs-on: ubuntu-latest
    needs: cloverExtension
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: cloverExtension.vsix
      
      - name: Download plugins
        working-directory: idePlugins
        run: python3 ./download.py

      - name: Upload ide plugins
        uses: actions/upload-artifact@v2.2.0
        with:
          name: idePlugins.zip
          path: idePlugins.zip

  ide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Install global dependencies
        run: |
          sudo apt update
          sudo apt install librsvg2-bin

      - name: Install dependencies and build theia
        working-directory: ide
        run: yarn

      - name: Package
        working-directory: ide
        run: | 
          make package
          zip ../ide.zip -r out

      - name: Upload idea
        uses: actions/upload-artifact@v2.2.0
        with:
          name: ide.zip
          path: ide.zip

  package:
    runs-on: ubuntu-latest
    needs: [ide, plugins]
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: ide.zip

      - uses: actions/download-artifact@v2
        with:
          name: idePlugins.zip
      
      - name: Download plugins
        working-directory: package
        run: make package

      - name: Upload deb
        uses: actions/upload-artifact@v2.2.0
        with:
          name: advancedClover.deb
          path: advancedClover.deb