name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Install global dependencies
        run: |
          sudo apt update
          sudo apt install librsvg2-bin
          sudo npm install -g yarn
          sudo yarn global add vsce

      - name: Install extension dependencies
        working-directory: cloverExtension
        run: yarn

      - name: Build extension
        working-directory: cloverExtension
        run: vsce package --yarn

      - name: Upload extension
        uses: actions/upload-artifact@v2.2.0
        with:
          name: cloverextension.vsix
          path: cloverExtension/cloverextension-0.0.1.vsix

      - name: Install ide dependencies
        working-directory: ide
        run: yarn

      - name: Build ide
        working-directory: ide
        run: yarn prepare

      - name: Build deb of cloverextension
        working-directory: ide
        run: make deb

      - name: Upload deb
        uses: actions/upload-artifact@v2.2.0
        with:
          name: cloverIDE.deb
          path: ide/deb.deb
